server.port = 7070
spring.application.name=bankappli-authorization

# Authorization Server
authorization.server.port = http://localhost:7080/

# Client
client.port = http://localhost:7180/

# Resource Server
resource.server.port = http://localhost:7280/

spring.datasource.url=jdbc:sqlserver://localhost:1433;instance=SQLEXPRESS;database=AuthorizationFramework;encrypt=true;trustServerCertificate=true;oginTimeout=30;
spring.datasource.username=sa
spring.datasource.password=K1ev2oo1
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.dialect = org.hibernate.dialect.SQLServerDialect
spring.jpa.database = SQL_SERVER
spring.jpa.show-sql=true

spring.boot.admin.client.url=http://localhost:9060
spring.boot.admin.client.enabled=true

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

spring.boot.admin.client.username=admin
spring.boot.admin.client.password=admin

spring.security.user.name=client
spring.security.user.password=client
spring.boot.admin.client.instance.metadata.user.name=${spring.security.user.name}
spring.boot.admin.client.instance.metadata.user.password=${spring.security.user.password}

#spring.boot.admin.routes.endpoints=env, metrics, trace, jolokia, info, configprops
